name: ozro_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  # router
  go_router: ^14.2.3
  # bloc state manager
  flutter_bloc: ^8.1.6
  # local storage: no sql db
  hive: ^2.2.3
  # url launcher
  url_launcher: ^6.3.0
  # equatable
  equatable: ^2.0.5
  # svg render
  flutter_svg: ^2.0.10+1
  # cached image
  cached_network_image: ^3.4.0
  # pin put:
  pinput: ^5.0.0
  # box
  gap: ^3.0.1
  # flash bar
  flash: ^3.1.1
  # interceptor
  dio: ^5.5.0+1
  dio_retry_plus: ^2.0.7
  # alice = chuck
  chuck_interceptor: ^2.1.2
#  chuck_interceptor:
#    git:
#      ref: main
#      url: https://github.com/Hayotbekferghana/chuck_interceptor.git
  # get it singleton
  get_it: ^7.7.0
  # path
  path_provider: ^2.1.4
  # firebase
  firebase_core: ^3.10.0
  firebase_analytics: ^11.4.0
  firebase_messaging: ^15.2.0
  firebase_crashlytics: ^4.3.0
  firebase_remote_config: ^5.3.0
  # local notification
  flutter_local_notifications: ^18.0.1
  # native splash
  flutter_native_splash: ^2.3.9
  # permission
  permission_handler: ^11.3.1
  http_parser: ^4.0.2
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  custom_pop_up_menu: ^1.2.4
  video_player: ^2.9.1
  yandex_mobileads: ^7.5.0
  shimmer: ^3.0.0
  device_info_plus: ^10.1.0
#  better_player: ^0.0.84
  widget_lifecycle: 1.0.0+1
  share_plus: ^10.1.3
  firebase_dynamic_links: ^6.0.11
  app_links: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

